# fly.toml app configuration file generated for buddyapp on 2023-07-19T10:30:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "buddyapp"
primary_region = "eze"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
